version: 1

# Build configuration
build:
  # Entry point for the build
  main: ./main.go

  # Build flags
  flags:
    - -trimpath

  # ldflags for version injection
  ldflags:
    - "-s -w"
    - "-X main.version={{.Env.VERSION}}"
    - "-X main.commit={{.Env.COMMIT}}"

  # Environment variables for the build
  env:
    - "CGO_ENABLED=0"

  # Binary name
  binary: soql-mcp

  # Target platforms
  goos:
    - linux
    - darwin
    - windows

  goarch:
    - amd64
    - arm64
